title: claudioSecco 
email: claudiosecco@hotmail.com.br
description: >- 
  Minha pagina pessoal com temas relacionados a finanças, música, computação, entre outros.
baseurl: "/website"
url: "https://claudiosecco.github.io"
github_username: claudiosecco

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
