title: claudioSecco 
email: claudiosecco@hotmail.com.br
description: >- 
  My personal site with finance, coding, music and other topics
baseurl: "/claudioSecco-personal-page"
url: "https://claudiosecco.github.io"
github_username: claudiosecco

collections:
  authors:
    output: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
